#ifdef GL_ES
precision mediump float;
#endif
// Galaxy
// Autogenerated from forth Haiku
// Generator by Stainless
// Haiku by DarkstarAG

uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

void main( void ) {

	float vars[32];
	float stack[8];
	 vec2 position = ( gl_FragCoord.xy / resolution.xy );
	vars[0] = 0.0000000;
	vars[1] = position.y;    // y
	vars[2] = 0.5000000;
	vars[1] = vars[1] - vars[2];
	vars[2] = vars[1];   // dup
	vars[1] = vars[2] * vars[1];
	vars[2] = position.x;     // x
	vars[3] = 0.5000000;
	vars[2] = vars[2] - vars[3];
	vars[3] = vars[2];   // dup
	vars[2] = vars[3] * vars[2];
	vars[1] = vars[2] + vars[1];
	vars[1] =  sqrt(vars[1]);
	vars[2] =  3.1415926535897931;
	vars[3] = 50.0000000;
	vars[2] = vars[3] * vars[2];
	vars[1] = vars[2] * vars[1];
	vars[1] =  floor(vars[1]);
	vars[2] = 10.0000000;
	vars[1] = mod(vars[1],vars[2]);
	vars[2] = 0.0000000;
	if (vars[2] == vars[1])  vars[1] = 1.0;   // ==	
		else vars[1]=0.0;
	vars[2] = position.y;    // y
	vars[3] = 0.5000000;
	vars[2] = vars[2] - vars[3];
	vars[3] = position.x;     // x
	vars[4] = 0.5000000;
	vars[3] = vars[3] - vars[4];
	vars[2] = atan(vars[2],vars[3]);
	vars[3] =  3.1415926535897931;
	vars[2] = vars[2] / vars[3];
	vars[3] = 120.0000000;
	vars[2] = vars[3] * vars[2];
	vars[3] = time;    // t
	vars[4] = -2.0000000;
	vars[3] = vars[4] * vars[3];
	vars[2] = vars[3] + vars[2];
	vars[2] =  floor(vars[2]);
	vars[3] = 10.0000000;
	vars[2] = mod(vars[2],vars[3]);
	vars[3] = 0.0000000;
	if (vars[3] == vars[2])  vars[2] = 1.0;   // ==	
		else vars[2]=0.0;
	if ((vars[2]!=0.0) || (vars[1]!=0.0))  vars[1] = 1.0;   // >	
		else vars[1]=0.0;
	vars[2] = 3.0000000;
	vars[1] = vars[1] / vars[2];
	vars[2] = position.y;    // y
	vars[3] = 0.5000000;
	vars[2] = vars[2] - vars[3];
	vars[3] = vars[2];   // dup
	vars[2] = vars[3] * vars[2];
	vars[3] = position.x;     // x
	vars[4] = 0.5000000;
	vars[3] = vars[3] - vars[4];
	vars[4] = vars[3];   // dup
	vars[3] = vars[4] * vars[3];
	vars[2] = vars[3] + vars[2];
	vars[2] =  sqrt(vars[2]);
	vars[3] = 0.1300000;
	if (vars[3] < vars[2])  vars[2] = 1.0;   // >	
		else vars[2]=0.0;
	vars[1] = vars[2] * vars[1];
	vars[2] = 0.6000000;
	vars[3] = 0.5000000;
	vars[4] = 2.0000000;
	vars[5] = 2.0000000;
	vars[6] = position.y;    // y
	vars[7] = 0.5000000;
	vars[6] = vars[6] - vars[7];
	vars[7] = vars[6];   // dup
	vars[6] = vars[7] * vars[6];
	vars[7] = position.x;     // x
	vars[8] = 0.5000000;
	vars[7] = vars[7] - vars[8];
	vars[8] = vars[7];   // dup
	vars[7] = vars[8] * vars[7];
	vars[6] = vars[7] + vars[6];
	vars[6] =  sqrt(vars[6]);
	vars[7] = 3.0000000;
	vars[6] = vars[7] * vars[6];
	vars[7] = position.y;    // y
	vars[8] = 0.5000000;
	vars[7] = vars[7] - vars[8];
	vars[8] = position.x;     // x
	vars[9] = 0.5000000;
	vars[8] = vars[8] - vars[9];
	vars[7] = atan(vars[7],vars[8]);
	vars[6] = vars[7] + vars[6];
	vars[5] = vars[6] * vars[5];
	vars[4] = vars[5] + vars[4];
	vars[4] =  sin(vars[4]);
	vars[3] = vars[4] * vars[3];
	vars[2] = vars[3] + vars[2];
	vars[3] = 1.0000000;
	vars[2] = vars[2] - vars[3];
	vars[2] = - vars[2];
	gl_FragColor = vec4(vars[0],vars[1],vars[2],1);

}