#ifdef GL_ES
precision mediump float;
#endif

// Waves interference
// Autogenerated from Forth Haiku
// Generator by Stainless
// Haiku by PPA

uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

void main( void ) {

	float vars[32];
	float stack[8];
	 vec2 position = ( gl_FragCoord.xy / resolution.xy );
	vars[0] = 0.5000000;
	vars[1] = 0.0000000;
	vars[2] = 10.0000000;
	vars[3] = 20.0000000;
	vars[4] = 0.5000000;
	vars[5] = 0.4500000;
	vars[6] = position.x;     // x
	vars[7] = position.y;    // y
	vars[8] = vars[7];	//rot 
	vars[7] = vars[5];	//rot 
	vars[5] = vars[6];	//rot 
	vars[6] = vars[8];	//rot 

	vars[6] = vars[6] - vars[7];
	vars[7] = vars[6];	//rot 
	vars[6] = vars[5];	//rot 
	vars[5] = vars[4];	//rot 
	vars[4] = vars[7];	//rot 

	vars[5] = vars[5] - vars[6];
	vars[6] = vars[5];   // dup
	vars[5] = vars[6] * vars[5];
	vars[6] = vars[5];   // swap
	vars[5] = vars[4];   // swap
	vars[4] = vars[6];   // swap
	vars[6] = vars[5];   // dup
	vars[5] = vars[6] * vars[5];
	vars[4] = vars[5] + vars[4];
	vars[4] =  sqrt(vars[4]);
	vars[5] = vars[4];   // dup
	stack[0] = vars[5];  // push
	vars[3] = vars[4] * vars[3];
	vars[4] = vars[3];   // swap
	vars[3] = vars[2];   // swap
	vars[2] = vars[4];   // swap
	vars[4] = time;    // t
	vars[3] = vars[4] * vars[3];
	vars[4] = vars[3];   // swap
	vars[3] = vars[2];   // swap
	vars[2] = vars[4];   // swap
	vars[2] = vars[2] - vars[3];
	vars[1] = vars[2] + vars[1];
	vars[1] =  cos(vars[1]);
	vars[0] = vars[1] * vars[0];
	vars[1] = stack[0];  // pop
	vars[0] = vars[0] / vars[1];
	vars[1] = 0.5000000;
	vars[2] = 0.0000000;
	vars[3] = 10.0000000;
	vars[4] = 100.0000000;
	vars[5] = 0.5000000;
	vars[6] = 0.5500000;
	vars[7] = position.x;     // x
	vars[8] = position.y;    // y
	vars[9] = vars[8];	//rot 
	vars[8] = vars[6];	//rot 
	vars[6] = vars[7];	//rot 
	vars[7] = vars[9];	//rot 

	vars[7] = vars[7] - vars[8];
	vars[8] = vars[7];	//rot 
	vars[7] = vars[6];	//rot 
	vars[6] = vars[5];	//rot 
	vars[5] = vars[8];	//rot 

	vars[6] = vars[6] - vars[7];
	vars[7] = vars[6];   // dup
	vars[6] = vars[7] * vars[6];
	vars[7] = vars[6];   // swap
	vars[6] = vars[5];   // swap
	vars[5] = vars[7];   // swap
	vars[7] = vars[6];   // dup
	vars[6] = vars[7] * vars[6];
	vars[5] = vars[6] + vars[5];
	vars[5] =  sqrt(vars[5]);
	vars[6] = vars[5];   // dup
	stack[0] = vars[6];  // push
	vars[4] = vars[5] * vars[4];
	vars[5] = vars[4];   // swap
	vars[4] = vars[3];   // swap
	vars[3] = vars[5];   // swap
	vars[5] = time;    // t
	vars[4] = vars[5] * vars[4];
	vars[5] = vars[4];   // swap
	vars[4] = vars[3];   // swap
	vars[3] = vars[5];   // swap
	vars[3] = vars[3] - vars[4];
	vars[2] = vars[3] + vars[2];
	vars[2] =  cos(vars[2]);
	vars[1] = vars[2] * vars[1];
	vars[2] = stack[0];  // pop
	vars[1] = vars[1] / vars[2];
	vars[0] = vars[1] + vars[0];
	vars[1] = 0.5000000;
	vars[2] = 2.0000000;
	vars[3] = 10.0000000;
	vars[4] = 20.0000000;
	vars[5] = 0.5000000;
	vars[6] = 0.4500000;
	vars[7] = position.x;     // x
	vars[8] = position.y;    // y
	vars[9] = vars[8];	//rot 
	vars[8] = vars[6];	//rot 
	vars[6] = vars[7];	//rot 
	vars[7] = vars[9];	//rot 

	vars[7] = vars[7] - vars[8];
	vars[8] = vars[7];	//rot 
	vars[7] = vars[6];	//rot 
	vars[6] = vars[5];	//rot 
	vars[5] = vars[8];	//rot 

	vars[6] = vars[6] - vars[7];
	vars[7] = vars[6];   // dup
	vars[6] = vars[7] * vars[6];
	vars[7] = vars[6];   // swap
	vars[6] = vars[5];   // swap
	vars[5] = vars[7];   // swap
	vars[7] = vars[6];   // dup
	vars[6] = vars[7] * vars[6];
	vars[5] = vars[6] + vars[5];
	vars[5] =  sqrt(vars[5]);
	vars[6] = vars[5];   // dup
	stack[0] = vars[6];  // push
	vars[4] = vars[5] * vars[4];
	vars[5] = vars[4];   // swap
	vars[4] = vars[3];   // swap
	vars[3] = vars[5];   // swap
	vars[5] = time;    // t
	vars[4] = vars[5] * vars[4];
	vars[5] = vars[4];   // swap
	vars[4] = vars[3];   // swap
	vars[3] = vars[5];   // swap
	vars[3] = vars[3] - vars[4];
	vars[2] = vars[3] + vars[2];
	vars[2] =  cos(vars[2]);
	vars[1] = vars[2] * vars[1];
	vars[2] = stack[0];  // pop
	vars[1] = vars[1] / vars[2];
	vars[2] = 0.5000000;
	vars[3] = 2.0000000;
	vars[4] = 10.0000000;
	vars[5] = 100.0000000;
	vars[6] = 0.5000000;
	vars[7] = 0.5500000;
	vars[8] = position.x;     // x
	vars[9] = position.y;    // y
	vars[10] = vars[9];	//rot 
	vars[9] = vars[7];	//rot 
	vars[7] = vars[8];	//rot 
	vars[8] = vars[10];	//rot 

	vars[8] = vars[8] - vars[9];
	vars[9] = vars[8];	//rot 
	vars[8] = vars[7];	//rot 
	vars[7] = vars[6];	//rot 
	vars[6] = vars[9];	//rot 

	vars[7] = vars[7] - vars[8];
	vars[8] = vars[7];   // dup
	vars[7] = vars[8] * vars[7];
	vars[8] = vars[7];   // swap
	vars[7] = vars[6];   // swap
	vars[6] = vars[8];   // swap
	vars[8] = vars[7];   // dup
	vars[7] = vars[8] * vars[7];
	vars[6] = vars[7] + vars[6];
	vars[6] =  sqrt(vars[6]);
	vars[7] = vars[6];   // dup
	stack[0] = vars[7];  // push
	vars[5] = vars[6] * vars[5];
	vars[6] = vars[5];   // swap
	vars[5] = vars[4];   // swap
	vars[4] = vars[6];   // swap
	vars[6] = time;    // t
	vars[5] = vars[6] * vars[5];
	vars[6] = vars[5];   // swap
	vars[5] = vars[4];   // swap
	vars[4] = vars[6];   // swap
	vars[4] = vars[4] - vars[5];
	vars[3] = vars[4] + vars[3];
	vars[3] =  cos(vars[3]);
	vars[2] = vars[3] * vars[2];
	vars[3] = stack[0];  // pop
	vars[2] = vars[2] / vars[3];
	vars[1] = vars[2] + vars[1];
	vars[2] = 0.5000000;
	vars[3] = 4.0000000;
	vars[4] = 10.0000000;
	vars[5] = 20.0000000;
	vars[6] = 0.5000000;
	vars[7] = 0.4500000;
	vars[8] = position.x;     // x
	vars[9] = position.y;    // y
	vars[10] = vars[9];	//rot 
	vars[9] = vars[7];	//rot 
	vars[7] = vars[8];	//rot 
	vars[8] = vars[10];	//rot 

	vars[8] = vars[8] - vars[9];
	vars[9] = vars[8];	//rot 
	vars[8] = vars[7];	//rot 
	vars[7] = vars[6];	//rot 
	vars[6] = vars[9];	//rot 

	vars[7] = vars[7] - vars[8];
	vars[8] = vars[7];   // dup
	vars[7] = vars[8] * vars[7];
	vars[8] = vars[7];   // swap
	vars[7] = vars[6];   // swap
	vars[6] = vars[8];   // swap
	vars[8] = vars[7];   // dup
	vars[7] = vars[8] * vars[7];
	vars[6] = vars[7] + vars[6];
	vars[6] =  sqrt(vars[6]);
	vars[7] = vars[6];   // dup
	stack[0] = vars[7];  // push
	vars[5] = vars[6] * vars[5];
	vars[6] = vars[5];   // swap
	vars[5] = vars[4];   // swap
	vars[4] = vars[6];   // swap
	vars[6] = time;    // t
	vars[5] = vars[6] * vars[5];
	vars[6] = vars[5];   // swap
	vars[5] = vars[4];   // swap
	vars[4] = vars[6];   // swap
	vars[4] = vars[4] - vars[5];
	vars[3] = vars[4] + vars[3];
	vars[3] =  cos(vars[3]);
	vars[2] = vars[3] * vars[2];
	vars[3] = stack[0];  // pop
	vars[2] = vars[2] / vars[3];
	vars[3] = 0.5000000;
	vars[4] = 4.0000000;
	vars[5] = 10.0000000;
	vars[6] = 100.0000000;
	vars[7] = 0.5000000;
	vars[8] = 0.5500000;
	vars[9] = position.x;     // x
	vars[10] = position.y;    // y
	vars[11] = vars[10];	//rot 
	vars[10] = vars[8];	//rot 
	vars[8] = vars[9];	//rot 
	vars[9] = vars[11];	//rot 

	vars[9] = vars[9] - vars[10];
	vars[10] = vars[9];	//rot 
	vars[9] = vars[8];	//rot 
	vars[8] = vars[7];	//rot 
	vars[7] = vars[10];	//rot 

	vars[8] = vars[8] - vars[9];
	vars[9] = vars[8];   // dup
	vars[8] = vars[9] * vars[8];
	vars[9] = vars[8];   // swap
	vars[8] = vars[7];   // swap
	vars[7] = vars[9];   // swap
	vars[9] = vars[8];   // dup
	vars[8] = vars[9] * vars[8];
	vars[7] = vars[8] + vars[7];
	vars[7] =  sqrt(vars[7]);
	vars[8] = vars[7];   // dup
	stack[0] = vars[8];  // push
	vars[6] = vars[7] * vars[6];
	vars[7] = vars[6];   // swap
	vars[6] = vars[5];   // swap
	vars[5] = vars[7];   // swap
	vars[7] = time;    // t
	vars[6] = vars[7] * vars[6];
	vars[7] = vars[6];   // swap
	vars[6] = vars[5];   // swap
	vars[5] = vars[7];   // swap
	vars[5] = vars[5] - vars[6];
	vars[4] = vars[5] + vars[4];
	vars[4] =  cos(vars[4]);
	vars[3] = vars[4] * vars[3];
	vars[4] = stack[0];  // pop
	vars[3] = vars[3] / vars[4];
	vars[2] = vars[3] + vars[2];
	gl_FragColor = vec4(vars[0],vars[1],vars[2],1);

}