#ifdef GL_ES
precision mediump float;
#endif

#extension GL_OES_standard_derivatives : enable

uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

// generated by @thi.ng/shader-ast

vec3 worleyDist(in vec3 _sn, in vec3 _so) {
return ((_sn * _sn) + (_so * _so));
}
vec3 permute3(in vec3 _sl) {
return mod((_sl * ((_sl * 34.0) + 1.0)), 289.0);
}
vec2 worley2(in vec2 _s2q, in float _s2r) {
vec3 _s2s = vec3(-1.0, 0.0, 1.0);
vec3 _s2t = vec3(-0.5, 0.5, 1.5);
vec2 _s2u = mod(floor(_s2q), 289.0);
vec2 _s2v = fract(_s2q);
vec3 _s2w = permute3((_s2s + _s2u.x));
vec3 _s2x = permute3(((_s2s + _s2u.y) + _s2w.x));
vec3 _s2y = worleyDist(((_s2v.x + 0.5) + ((fract((_s2x * 0.14285714285714285)) - 0.42857142857142855) * _s2r)), ((_s2v.y - _s2t) + (((mod(floor((_s2x * 0.14285714285714285)), 7.0) * 0.14285714285714285) - 0.42857142857142855) * _s2r)));
_s2x = permute3((_s2s + (_s2u.y + _s2w.y)));
vec3 _s2z = worleyDist(((_s2v.x + -0.5) + ((fract((_s2x * 0.14285714285714285)) - 0.42857142857142855) * _s2r)), ((_s2v.y - _s2t) + (((mod(floor((_s2x * 0.14285714285714285)), 7.0) * 0.14285714285714285) - 0.42857142857142855) * _s2r)));
_s2x = permute3((_s2s + (_s2u.y + _s2w.z)));
vec3 _s30 = worleyDist(((_s2v.x + -1.5) + ((fract((_s2x * 0.14285714285714285)) - 0.42857142857142855) * _s2r)), ((_s2v.y - _s2t) + (((mod(floor((_s2x * 0.14285714285714285)), 7.0) * 0.14285714285714285) - 0.42857142857142855) * _s2r)));
vec3 _s31 = min(_s2y, _s2z);
_s2z = min(max(_s2y, _s2z), _s30);
_s2y = min(_s31, _s2z);
_s2z = max(_s31, _s2z);
_s2y.xy = ((_s2y.x < _s2y.y) ? _s2y.xy : _s2y.yx);
_s2y.xz = ((_s2y.x < _s2y.z) ? _s2y.xz : _s2y.zx);
_s2y.yz = min(_s2y.yz, _s2z.yz);
_s2y.y = min(min(_s2y.y, _s2y.z), _s2z.x);
return sqrt(_s2y.xy);
}

void main( void ) {

	vec2 uv = ( gl_FragCoord.xy / resolution.xy ) + mouse / 0.2;
	uv.x *= resolution.x / resolution.y;

	vec2 n = worley2(uv*10., sin(time)*0.5+0.5);

	gl_FragColor = vec4(vec3(n.y-n.x), 1.0);

}